import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
  },
  input: {
    height: 48,
    borderRadius: 5,
    overflow: "hidden",
    backgroundColor: "white",
    marginTop: 10,
    marginBottom: 10,
    marginLeft: 30,
    marginRight: 30,
    paddingLeft: 16,
  },
  container: {
    flex: 1,
    backgroundColor: "#75D9FE",
  },
  main_content: {
    flex: 1,
    marginTop: 150,
    backgroundColor: "#3C6D82",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    alignItems: "center",
  },
  question_header: {
    fontSize: 13,
    fontWeight: "300",
    color: "#fff",
    paddingTop: 70,
  },
  question_title: {
    fontSize: 24,
    fontWeight: "500",
    color: "#fff",
    paddingTop: 30,
  },
  question_title: {
    fontSize: 24,
    fontWeight: "500",
    color: "#fff",
    paddingTop: 30,
  },
  question_content: {
    fontSize: 24,
    fontWeight: "500",
    color: "#fff",
    paddingTop: 30,
    flex: 1,
    flexDirection: "row",
    //flexWrap: "wrap",
  },
  question_title_word: {
    fontSize: 20,
    fontWeight: "800",
    color: "#fff",
    paddingTop: 30,
    textDecorationLine: "underline",
  },
  question_content_meaning_word: {
    fontSize: 18,
    fontWeight: "500",
    color: "#fff",
    paddingTop: 30,
    textDecorationStyle: "dotted",
    textDecorationColor: "white",
    textDecorationLine: "underline",
    padding: 10,
  },
  question_content_popover_word: {
    fontSize: 16,
    fontWeight: "500",
    color: "#3C6D82",
    textDecorationStyle: "dotted",
    textDecorationColor: "white",
    textDecorationLine: "underline",
    padding: 10,
  },
  question_outer_missing_word: {
    fontSize: 16,
    fontWeight: "800",
    backgroundColor: "#fff",
    //flex: 1,
    borderRadius: 15,
    padding: 15,
    color: "#3C6D82",
    height: 50,
    marginTop: 15,
  },
  question_content_missing_word: {
    fontSize: 16,
    fontWeight: "800",

    color: "#3C6D82",
  },
  question_content_empty_word: {
    fontSize: 16,
    fontWeight: "800",
    color: "#fff",
    width: 100,
    textDecorationLine: "underline",
    marginTop: 32,
  },
  question_answer: {
    fontSize: 24,
    fontWeight: "500",
    color: "#fff",
    //paddingTop: -190,
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    padding: 20,
    marginTop: -220,
    justifyContent: "center",
    alignItems: "center",
  },
  button_answer: {
    backgroundColor: "#fff",
    //flex: 1,
    borderRadius: 15,

    padding: 15,
    color: "#3C6D82",
    height: 50,
    width: 100,
    alignItems: "center",
    marginRight: 20,
    marginTop: 20,
  },
  answer: {
    color: "#3C6D82",
    fontSize: 14,
    fontWeight: "800",
  },
  button_continue: {
    backgroundColor: "#6391A6",
    borderRadius: 25,
    padding: 15,
    height: 50,
    width: 300,
    alignItems: "center",
    marginBottom: 50,
  },
  text_continue: {
    color: "#fff",
    fontWeight: "800",
  },
  button_check_answer: {
    backgroundColor: "#17E3E8",
    borderRadius: 25,
    padding: 15,
    height: 50,
    width: 300,
    alignItems: "center",
    marginBottom: 40,
    marginTop: 20,
  },
  text_check_answer: {
    color: "#fff",
    fontWeight: "800",
  },
  outer_result: {
    backgroundColor: "#3C6D82",
    borderTopRightRadius: 30,
    borderTopLeftRadius: 30,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  outer_result_correct: {
    backgroundColor: "#17E3E8",
    borderTopRightRadius: 30,
    borderTopLeftRadius: 30,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  outer_result_wrong: {
    backgroundColor: "#FF808A",
    borderTopRightRadius: 30,
    borderTopLeftRadius: 30,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  button_answer_wrong: {
    backgroundColor: "#fff",
    //flex: 1,
    borderRadius: 25,
    padding: 15,
    height: 50,
    width: 300,
    alignItems: "center",
    marginBottom: 40,
    marginTop: 20,
  },
  text_answer_wrong: {
    color: "#FF808A",
    fontWeight: "800",
  },
  button_answer_correct: {
    backgroundColor: "#fff",
    //flex: 1,
    borderRadius: 25,
    padding: 15,
    height: 50,
    width: 300,
    alignItems: "center",
    marginBottom: 40,
    marginTop: 20,
  },
  text_answer_correct: {
    color: "#17E3E8",
    fontWeight: "800",
  },
  text_result: {
    color: "#fff",
    fontWeight: "800",
    alignItems: "flex-start",
    marginTop: 30,
  },
});
